### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by nzhang258** [onion-liu/aahq-dataset#1]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdnb.artstation.com', port=443)
I try some solutions like 'https://blog.csdn.net/weixin_42210687/article/details/103480208', but still not work well. Sorry to bother you that do you know this prob?
thanks.

**Comment by onion-liu** [comment]
Try to visit https://www.artstation.com in your browser. If you can not access the website, maybe you need a VPN.

**Comment by nzhang258** [comment]
I can visit this website in browser, but if use python requests.get(url) I will meet the error. And I can also visit the image_url in 'AADQ-dataset.json', but also cannot in requests.get(image_url)

**Comment by nzhang258** [comment]
> Try to visit https://www.artstation.com in your browser. If you can not access the website, maybe you need a VPN.

I can visit this website in browser, but if use python requests.get(url) I will meet the error. And I can also use browser to visit the image_url in 'AADQ-dataset.json', but also cannot in requests.get(image_url)

**Comment by onion-liu** [comment]
> > Try to visit https://www.artstation.com in your browser. If you can not access the website, maybe you need a VPN.
> 
> I can visit this website in browser, but if use python requests.get(url) I will meet the error. And I can also use browser to visit the image_url in 'AADQ-dataset.json', but also cannot in requests.get(image_url)

Does `requests.get(url)` work for image urls in other websites (such as baidu.com)?

**Comment by nzhang258** [comment]
So, can you please run this test.py? I want to check this prob is caused by my own network env or this website~ Thanks a lot. 

import requests
url='https://cdnb.artstation.com/p/assets/images/images/032/076/469/4k/dropofcreativity-art-redraw.jpg'
res=requests.get(url)
print(res.status_code)

**Comment by nzhang258** [comment]
> > > Try to visit https://www.artstation.com in your browser. If you can not access the website, maybe you need a VPN.
> > 
> > 
> > I can visit this website in browser, but if use python requests.get(url) I will meet the error. And I can also use browser to visit the image_url in 'AADQ-dataset.json', but also cannot in requests.get(image_url)
> 
> Does `requests.get(url)` work for image urls in other websites (such as baidu.com)?

Yes, I can get output
'<Response [200]>'

**Comment by onion-liu** [comment]
> So, can you please run this test.py? I want to check this prob is caused by my own network env or this website~ Thanks a lot.
> 
> import requests url='https://cdnb.artstation.com/p/assets/images/images/032/076/469/4k/dropofcreativity-art-redraw.jpg' res=requests.get(url) print(res.status_code)

It works for me! Maybe you need to check your network.
![image](https://user-images.githubusercontent.com/6346064/145168240-826c0a64-9da6-40c4-afc9-ea54091d19ad.png)

**Comment by nzhang258** [comment]
> > So, can you please run this test.py? I want to check this prob is caused by my own network env or this website~ Thanks a lot.
> > import requests url='https://cdnb.artstation.com/p/assets/images/images/032/076/469/4k/dropofcreativity-art-redraw.jpg' res=requests.get(url) print(res.status_code)
> 
> It works for me! Maybe you need to check your network. ![image](https://user-images.githubusercontent.com/6346064/145168240-826c0a64-9da6-40c4-afc9-ea54091d19ad.png)

OK,thanks!
