### ISSUE TITLE
One image missing and it interrupted the download

### ISSUE THREAD

**Issue by kasim0226** [onion-liu/aahq-dataset#3]
I download the dataset several times. It always terminal on the following image:

FileNotFoundError: [Errno 2] No such file or directory: './raw\\033_811_848_4k_elina-mei-rz75hvsungrap8uuohcswbpuqlidf3rxmq7ehpycvqpb5pwzyreu2s3hc7tsqjfns9pekzogzfcevvdzdcrwqyb2kaqidmbzmksxyfnhw1ddfxqa6gmvowbgakw9soj3t4dugditsv7sunzzxakqysinxjd0yxg1xe7bebqatuyvt0mcgl21ejhnwdplxnwtb5oe3uwf.jpg

**Comment by onion-liu** [comment]
It seems your OS is Windows, in which the maximum path length is limited to 260 characters. Renaming `imgname` [here](https://github.com/onion-liu/aahq-dataset/blob/main/download.py#L31) may help.

ref: https://stackoverflow.com/questions/4677234/python-ioerror-exception-when-creating-a-long-file
