### ISSUE TITLE
Question: why first transform() to large size then resize() to smaller size?

### ISSUE THREAD

**Issue by peacej** [onion-liu/aahq-dataset#4]
With the default arguments in image_align(), you first transform to a large size (4096x4096) and then resize to a smaller size (1024x1024). Why not just directly transform into the smaller size? 

BTW, thank you so much for this awesome tool!

**Comment by onion-liu** [comment]
The alignment code is borrowed from FFHQ (https://github.com/NVlabs/ffhq-dataset/blob/4826aa6ea77aa7f1a7802b938ed7c40afb985cda/download_ffhq.py#L370). I think this process will avoid some quality loss during image resizing. (The final resizing process used PIL.Image.ANTIALIAS mode).

**Comment by onion-liu** [comment]
For more details, please see Appendix C in the ProGAN paper (https://arxiv.org/pdf/1710.10196.pdf).
